#!/usr/bin/ruby

require 'rubygems'

ENV['BUNDLE_GEMFILE'] = "#{__dir__}/../Gemfile"
require 'bundler/setup'

require_relative '../lib/doors.rb'

$log_level = ENV['LOG_LEVEL']&.downcase&.to_sym || :off

Doors::CLI.new(ARGV).call
