#!/home/jakub/.rvm/gems/ruby-2.5.3/wrappers/ruby

require 'rubygems'
require 'bundler/setup'

require_relative '../lib/doors.rb'

$log_level = ENV['LOG_LEVEL']&.downcase&.to_sym || :info

Doors::CLI.new(ARGV).call
